artifact_uri: file:///C:/Users/mande/OneDrive/Desktop/day2MLOPS/mlruns_local/0/866bc7af8ec94aa7878d42c323154645/artifacts
end_time: 1780550374894
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 866bc7af8ec94aa7878d42c323154645
run_name: sassy-trout-236
source_name: ''
source_type: 4
source_version: ''
start_time: 1780550374277
status: 4
tags: []
user_id: mande
