artifact_location: file:///C:/Users/mande/OneDrive/Desktop/day2MLOPS/mlruns_local/0/models/m-b5cdcb0f837b43e2b4772f8d488a16fd/artifacts
creation_timestamp: 1780550457124
experiment_id: '0'
last_updated_timestamp: 1780550457264
model_id: m-b5cdcb0f837b43e2b4772f8d488a16fd
model_type: null
name: model
source_run_id: b337188fe21c4c08995d403a92939512
status: 3
status_message: null
